CREATE SCHEMA KILLER;
USE KILLER;
-- DROP TABLE IF EXISTS --> ELIMNA TABELLA 
-- CREAZIONE TABELLA
CREATE TABLE KILLER(
ID_KILLER INT
,  NOME VARCHAR(50)
,  COGNOME VARCHAR(50)
,  GENERE CHAR(1)
,  NUM_VITTIME INT
,  STATUS_MORTO INT
,  CONSTRAINT PK_KILLER PRIMARY KEY (ID_KILLER)
);


-- CREAZIONE TABELLA AREA_GEOGRAFICA
CREATE TABLE AREA_GEOGRAFICA(
ID_AREA INT
,  NOME_AREA VARCHAR(50)
,  CONSTRAINT AREA_GEOGRAFICA PRIMARY KEY (ID_AREA)
);

-- CREAZIIONE TABELLA ARMA
CREATE TABLE ARMA(
ID_ARMA INT
,  NOME_ARMA VARCHAR(50)
,  CONSTRAINT PK_ARMA PRIMARY KEY (ID_ARMA)
);

-- CREAZIONE TABELLA VITTIMA 
CREATE TABLE VITTIMA(
ID_VITTIMA INT
,  NOME VARCHAR(50)
,  COGNOME VARCHAR(50)
,  ANNI INT 
,  GENERE CHAR(1)
,  CONSTRAINT PK_VITTIMA PRIMARY KEY (ID_VITTIMA)
);

-- CREAZIONE TABELLA DELITTO
CREATE TABLE DELITTO(
ID_DELITTO INT
,  ID_KILLER INT
,  ID_AREA INT
,  ID_ARMA INT
,  ID_VITTIMA INT
,  CONSTRAINT PK_DELITTO PRIMARY KEY (ID_DELITTO)
,  CONSTRAINT FK_KILLER_DELITTO FOREIGN KEY (ID_KILLER) REFERENCES KILLER (ID_KILLER)
,  CONSTRAINT FK_AREA_GEOGRAFICA_DELITTO FOREIGN KEY (ID_AREA) REFERENCES AREA_GEOGRAFICA (ID_AREA)
,  CONSTRAINT FK_ARMA_DELITTO FOREIGN KEY (ID_ARMA) REFERENCES ARMA (ID_ARMA)
,  CONSTRAINT FK_VITTIMA_DELITTO FOREIGN KEY (ID_VITTIMA) REFERENCES VITTIMA (ID_VITTIMA)
);

-- POPOLAMENTO TABELLA KILLER
INSERT INTO KILLER VALUES
(1,"Dexter", "Morgan","M", 2,0)
,(2,"Beatrix" ,"Kiddo","F",1,0)
,(3,"Walter","White","M",1,1)
,(4,"John", "RED","M",2,1)
,(5,"Hannibal","Lecter","M",1,1)
,(6,"Freddy", "Kruger","M",1,0)
,(7,"It","It","N",2,0);

SELECT *
FROM KILLER;

-- POPOLAMENTO TABELLA AREA_GEOGRAFICA
INSERT INTO AREA_GEOGRAFICA VALUES
(1,"America")
,(2,"Europa")
,(3,"Asia")
,(4,"Africa");

SELECT *
FROM AREA_GEOGRAFICA;

-- POPOLAMENTO TABELLA ARMA
INSERT INTO ARMA VALUES
(1,"Coltello")
,(2,"Katana")
,(3,"Droghe")
,(4,"Coltello")
,(5,"Denti")
,(6,"Lame")
,(7,"Palloncini");

SELECT *
FROM ARMA;

-- POPOLAMENTO TABELLA VITTIMA
INSERT INTO VITTIMA VALUES
(1,"Mario","Luigi",49,"M")
,(2,"Luigi","Mario",34,"M")
,(3,"Sara","Rasa",35,"F")
,(4,"Giulio","Liogiu",43,"M")
,(5,"Carlo","Locarl",26,"M")
,(6,"Federica","Ricafede",67,"F")
,(7,"Vittoria","Persa",73,"F")
,(8,"Riccardo","Bettino",15,"M")
,(9,"Tizio","Caio",53,"M");

SELECT *
FROM VITTIMA;